adminUser: admin
adminPassword: password
admin: {}
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-kube-prometheus-prometheus.warnet-logging:9090
      uid: PBFA97CFB590B2093
    - name: Loki
      type: loki
      url: http://loki-gateway.warnet-logging:80
      uid: P8E80F9AEF21F6940
