apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bitcoincore.fullname" . }}
  labels:
    {{- include "bitcoincore.labels" . | nindent 4 }}
data:
  bitcoin.conf: |
    {{- if eq .Values.chain "regtest" }}
      {{- tpl .Values.regtestConfig . | nindent 4 }}
    {{- end }}
    {{- if eq .Values.chain "regtestold" }}
      {{- tpl .Values.regtestConfigOld . | nindent 4 }}
    {{- end }}
    {{- .Values.baseConfig | nindent 4 }}
    {{- .Values.config | nindent 4 }}
    {{- range .Values.connect }}
      {{- print "connect=" . | nindent 4}}
    {{- end }}